
version: '3'

services:

  cfgsvr3:
    container_name: cfgsvr1-yh-test
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3:/data/db

volumes:
  cfgsvr3: {}
